# Generated by Django 4.2 on 2024-12-11 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Funcionarios',
        ),
    ]
